apiVersion: v1
kind: Service
metadata:
  name: frontend-service-service
  namespace: production
spec:
  selector:
    app: frontend-service-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80