apiVersion: v1
kind: Service
metadata:
  name: users-db-service
  namespace: production
spec:
  selector:
    app: users-db-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5431
    targetPort: 5432