apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: production
spec:
  selector:
    app: pgadmin-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 5433
    targetPort: 5433
    nodePort: 30033