apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: production
spec:
  selector:
    app: grafana-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 3000