apiVersion: v1
kind: Service
metadata:
  name: couriers-service-service
  namespace: production
spec:
  selector:
    app: couriers-service-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002