apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  namespace: production
spec:
  selector:
    app: gateway-service-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000