apiVersion: v1
kind: Service
metadata:
  name: couriers-db-service
  namespace: production
spec:
  selector:
    app: couriers-db-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5434
    targetPort: 5432