apiVersion: v1
kind: Service
metadata:
  name: users-service-service
  namespace: production
spec:
  selector:
    app: users-service-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001